name: rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bamtools=2.5.1
  - bcftools=1.9
  - bioconductor-diffbind=2.16.0
  - fastqc=0.11.9
  - igvtools=2.5.3
  - rseqc=3.0.1
  - samtools=1.10
  - sra-tools=2.10.8
  - star=2.7.5a
  - tpmcalculator=0.0.3
  - trimmomatic=0.39
  - ucsc-gtftogenepred=377
  - ucsc-genepredtobed=377
